use ratatui::style::{Color, Modifier, Style};

#[derive(Debug, Clone, Copy)]
pub struct Theme {
    pub panel_border: Style,
    pub panel_border_active: Style,
    pub title: Style,
    pub text: Style,
    pub text_muted: Style,
    pub transcript_divider: Style,
    pub card_prefix: Style,
    pub operational_prefix: Style,
    pub operational_label: Style,
    pub operational_text: Style,
    pub markdown_heading_1: Style,
    pub markdown_heading_2: Style,
    pub markdown_heading_3: Style,
    pub markdown_quote: Style,
    pub markdown_code: Style,
    pub markdown_code_block: Style,
    pub markdown_link: Style,
    pub markdown_emphasis: Style,
    pub markdown_strong: Style,
    pub markdown_strike: Style,
    pub markdown_list_marker: Style,
    pub user_accent: Style,
    pub assistant_accent: Style,
    pub system_accent: Style,
    pub tool_accent: Style,
    pub label: Style,
    pub success: Style,
    pub warning: Style,
    pub error: Style,
    pub info: Style,
}

pub const TUI_THEME: Theme = Theme {
    panel_border: Style::new().fg(Color::DarkGray),
    panel_border_active: Style::new().fg(Color::Blue),
    title: Style::new().fg(Color::White).add_modifier(Modifier::BOLD),
    text: Style::new().fg(Color::White),
    text_muted: Style::new().fg(Color::DarkGray),
    transcript_divider: Style::new().fg(Color::DarkGray),
    card_prefix: Style::new().fg(Color::DarkGray),
    operational_prefix: Style::new().fg(Color::DarkGray),
    operational_label: Style::new().fg(Color::Gray).add_modifier(Modifier::BOLD),
    operational_text: Style::new().fg(Color::Gray),
    markdown_heading_1: Style::new().fg(Color::White).add_modifier(Modifier::BOLD),
    markdown_heading_2: Style::new().fg(Color::Cyan).add_modifier(Modifier::BOLD),
    markdown_heading_3: Style::new().fg(Color::Gray).add_modifier(Modifier::BOLD),
    markdown_quote: Style::new().fg(Color::Green),
    markdown_code: Style::new().fg(Color::Yellow),
    markdown_code_block: Style::new().fg(Color::Yellow),
    markdown_link: Style::new()
        .fg(Color::Blue)
        .add_modifier(Modifier::UNDERLINED),
    markdown_emphasis: Style::new().add_modifier(Modifier::ITALIC),
    markdown_strong: Style::new().add_modifier(Modifier::BOLD),
    markdown_strike: Style::new().add_modifier(Modifier::CROSSED_OUT),
    markdown_list_marker: Style::new().fg(Color::Cyan).add_modifier(Modifier::BOLD),
    user_accent: Style::new().fg(Color::Cyan).add_modifier(Modifier::BOLD),
    assistant_accent: Style::new().fg(Color::Green).add_modifier(Modifier::BOLD),
    system_accent: Style::new().fg(Color::Yellow).add_modifier(Modifier::BOLD),
    tool_accent: Style::new().fg(Color::Magenta).add_modifier(Modifier::BOLD),
    label: Style::new().fg(Color::Blue).add_modifier(Modifier::BOLD),
    success: Style::new().fg(Color::Green).add_modifier(Modifier::BOLD),
    warning: Style::new().fg(Color::Yellow).add_modifier(Modifier::BOLD),
    error: Style::new().fg(Color::Red).add_modifier(Modifier::BOLD),
    info: Style::new().fg(Color::Cyan).add_modifier(Modifier::BOLD),
};
